- name: Generate yaml files
  hosts: localhost
  gather_facts: false

  vars:
    netbox_url: "{{ lookup('env', 'NETBOX_API_URL') }}"
    netbox_token: "{{ lookup('env', 'NETBOX_API_TOKEN') }}"

  tasks:
    - name: Extract list of site names
      ansible.builtin.set_fact:
        sites_names: >-
          {{
            query('netbox.netbox.nb_lookup', 'sites',
                  api_endpoint=netbox_url,
                  token=netbox_token)
            | map(attribute='value')
            | list
          }}
    - name: Define the site files directory
      ansible.builtin.set_fact:
        site_files_dir: "{{ playbook_dir }}/../Organization/Sites"

    - name: Write each tenant to a YAML file
      ansible.builtin.copy:
        dest: "{{ site_files_dir }}/{{ item.name | replace(' ', '_') }}.yml"
        content: |
          name: "{{ item.name }}"
          status: "{{ item.status.label }}"
          region: "{{ item.region.name }}"
          site_group: "{{ item.group.name }}"
          tenant: "{{ item.tenant.name }}"
        mode: '0644'
      loop: "{{ sites_names }}"
      loop_control:
        label: "{{ item.name }}"
