- name: Generate yaml files
  hosts: localhost
  gather_facts: false

  vars:
    netbox_url: "{{ lookup('env', 'NETBOX_API_URL') }}"
    netbox_token: "{{ lookup('env', 'NETBOX_API_TOKEN') }}"

  roles:
    - role: netbox_yaml_files
