---
- name: Create regions
  ansible.builtin.include_tasks: regions.yml
  tags: regions

- name: Create sites
  ansible.builtin.include_tasks: sites.yml
  tags: sites

- name: Create tenants
  ansible.builtin.include_tasks: tenants.yml
  tags: tenants

- name: Create locations
  ansible.builtin.include_tasks: locations.yml
  tags: locations
