- name: Extract list of site names
  ansible.builtin.set_fact:
    sites_names: >-
      {{
        query('netbox.netbox.nb_lookup', 'sites',
              api_endpoint=netbox_url,
              token=netbox_token)
        | map(attribute='value')
        | list
      }}
- name: Define the site files directory
  ansible.builtin.set_fact:
    site_files_dir: "{{ playbook_dir }}/../Organization/Sites"

- name: Write each tenant to a YAML file
  ansible.builtin.template:
    src: "sites.j2"
    dest: "{{ site_files_dir }}/{{ item.name | replace(' ', '_') }}.yml"
    mode: '0644'
  loop: "{{ sites_names }}"
  loop_control:
    label: "{{ item.name }}"
