---
- name: Define the site files directory
  ansible.builtin.set_fact:
    site_files_dir: "{{ playbook_dir }}/../Organization/Sites"

- name: Find al sites YAML files
  ansible.builtin.find:
    paths: "{{ site_files_dir }}"
    patterns:
      - "*.yml"
      - "*.yaml"
  register: site_files

- name: Initialize sites_raw
  ansible.builtin.set_fact:
    sites: []

- name: Load YAML content from each site file
  ansible.builtin.set_fact:
    sites: "{{ sites + [lookup('file', item.path) | from_yaml] }}"
  loop: "{{ site_files.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: Configure sites
  netbox.netbox.netbox_site:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.name }}"
      description: "{{ item.description | default(omit) }}"
      region: "{{ item.region }}"
      status: "{{ item.status }}"
      tenant: "{{ item.tenant }}"
      site_group: "{{ item.site_group }}"
    state: present
  loop: "{{ sites }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.tenant in tenant_names
    - item.region in regions_names
    - item.site_group in site_groups_names
