- name: Create Context
  netbox.netbox.netbox_config_context:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data: "{{ raw_config_context }}"
    state: present
  register: config_context_output
  tags: create_config_context
