- name: Delete context
  netbox.netbox.netbox_config_context:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data: "{{ raw_config_context }}"
    state: absent
  register: config_context_output
  tags: delete_config_context
